/**
 * The fixture store — one deterministic, in-memory assembly of the whole canonical
 * dataset (docs/14-frontend-implementation-plan.md §4.2). Built once per server
 * process from a fixed seed; every mock route handler reads from this singleton.
 *
 * Order matters: taxonomy -> records -> documents (needs records) -> attribute values
 * (needs records + document bindings) -> review tasks (needs attribute values) ->
 * runs -> eval runs. Dashboard/queue aggregates are all *computed* from this data,
 * never hand-typed (risk F-3).
 */
import { createRng } from "./rng";
import { TAXONOMY } from "./taxonomy";
import { generateRecordSkeletons, type RecordSkeleton } from "./records";
import { generateDocuments } from "./documents";
import { generateAttributeValues } from "./attribute-values";
import { generateReviewTasks, type RecordIndexEntry } from "./review-tasks";
import { generateRuns } from "./runs";
import { generateEvalRuns } from "./eval-runs";
import type {
  AttributeValueStatus,
  EvidenceWire,
  ProvenanceKind,
  UnknownReason,
} from "@/lib/contracts/attribute-value";
import type { ClassRefWire, RecordStatus } from "@/lib/contracts/record";
import type { ReviewReasonCode } from "@/lib/contracts/review";

const SEED = 0x0f5f0e5c; // "F5F0E5C" — arbitrary, fixed. Never change without a reason.
const RECORD_COUNT = 240;

/** The full shape every object generated by mocks/fixtures/attribute-values.ts
 *  actually has — see the `[key: string]: unknown` extras noted there (record_id,
 *  attribute_code, attribute_name, risk_tier) plus the real wire fields. Kept explicit
 *  (not relying on an index signature) so downstream call sites get real structural
 *  checking instead of `unknown`. */
export interface WireAttrValue {
  id: string;
  record_id: string;
  attribute_code: string;
  attribute_name: string;
  risk_tier: 0 | 1 | 2 | 3;
  attribute: {
    code: string;
    name: string;
    datatype: string;
    risk_tier: 0 | 1 | 2 | 3;
    is_mandatory: boolean;
  };
  status: AttributeValueStatus;
  value_display: string | null;
  value_canonical: Record<string, unknown> | null;
  value_raw: string | null;
  unknown_reason: UnknownReason | null;
  provenance_kind: ProvenanceKind | null;
  confidence: number | null;
  evidence: EvidenceWire[];
  verification: {
    verdict: string;
    deterministic_check: string;
    rationale: string;
    verifier_model: string;
  } | null;
  created_at: string;
}

/** Matches mocks/fixtures/review-tasks.ts's `buildTask()` return shape. */
export interface WireReviewTask {
  id: string;
  record_id: string;
  record_mpn: string;
  record_description: string;
  attribute_value_id: string;
  attribute_code: string;
  attribute_name: string;
  risk_tier: 0 | 1 | 2 | 3;
  reason_code: ReviewReasonCode;
  state: "open" | "claimed" | "resolved" | "skipped";
  priority: number;
  assigned_to: string | null;
  proposed_value: WireAttrValue | null;
  rejection_reason: string | null;
  document_version_id: string | null;
  page: number | null;
  similar_task_count: number;
  opened_at: string;
  closed_at: string | null;
}

/** Matches mocks/fixtures/documents.ts's `buildDocumentWire()` return shape. */
export interface WireDocument {
  document_version_id: string;
  document_id: string;
  publisher: string;
  title: string;
  doc_type: string;
  page_count: number;
  parse_status: string;
  bound_record_count: number;
  first_seen_at: string;
  content_hash: string;
  source_url: string | null;
  fetched_at: string;
  effective_date: string | null;
  parse_quality: number | null;
  has_text_layer: boolean;
  used_ocr: boolean;
  pages: { n: number; width_px: number; height_px: number; dpi: number }[];
  regions_summary: { table_count: number; row_count: number };
}

function buildStore() {
  const rng = createRng(SEED);

  const skeletons = generateRecordSkeletons(rng, RECORD_COUNT);
  const docsResult = generateDocuments(rng, skeletons);
  const attributeValues = generateAttributeValues(
    rng,
    skeletons,
    docsResult.bindingsByRecord,
    docsResult.unparseableDocumentVersionId,
    docsResult.wrongRowEvidence,
  ) as WireAttrValue[];

  // `attrsByRecord` is the *current* one-per-attribute set that drives completeness,
  // RecordSummary counts, and GET /records/{id}'s `attributes` list — it must exclude
  // SUPERSEDED entries (injected by attribute-values.ts's `injectSupersessionChains`),
  // which exist only for individual lookup via `attributeValueById` below (the
  // `/attributes/{id}/explain` and `/attributes/{id}/history` routes), never as part of
  // a record's current attribute set.
  const attrsByRecord = new Map<string, WireAttrValue[]>();
  for (const av of attributeValues) {
    if (av.status === "SUPERSEDED") continue;
    const list = attrsByRecord.get(av.record_id) ?? [];
    list.push(av);
    attrsByRecord.set(av.record_id, list);
  }

  const skeletonById = new Map(skeletons.map((s) => [s.id, s]));

  const records = skeletons.map((skeleton) =>
    buildRecordSummary(
      skeleton,
      attrsByRecord.get(skeleton.id) ?? [],
      rng,
      docsResult.bindingsByRecord,
    ),
  );
  const recordDetails = new Map(
    records.map((summary, i) => [
      summary.id,
      {
        ...summary,
        bindings: (docsResult.bindingsByRecord[skeletons[i].id] ?? []).map((b) => ({
          document_version_id: b.documentVersionId,
          region_id: b.regionId,
          confidence: b.confidence,
          signals: b.signals,
        })),
        attributes: (attrsByRecord.get(skeletons[i].id) ?? []).map(stripInternalFields),
      },
    ]),
  );

  const recordIndex = new Map<string, RecordIndexEntry>(
    skeletons.map((s) => [s.id, { id: s.id, mpnRaw: s.mpnRaw, descriptionRaw: s.descriptionRaw }]),
  );
  const bindingByRecord = new Map<string, { documentVersionId: string; page: number }>(
    Object.entries(docsResult.bindingsByRecord).map(([id, bindings]) => [
      id,
      { documentVersionId: bindings[0].documentVersionId, page: bindings[0].page },
    ]),
  );

  const reviewTasks = generateReviewTasks(
    rng,
    attributeValues,
    recordIndex,
    bindingByRecord,
  ) as WireReviewTask[];

  const runs = generateRuns();
  const evalRuns = generateEvalRuns();

  const attributeValueById = new Map(attributeValues.map((av) => [av.id, av]));
  const documentByVersionId = new Map(
    (docsResult.documents as WireDocument[]).map((d) => [d.document_version_id, d]),
  );

  return {
    taxonomy: TAXONOMY,
    skeletonById,
    records,
    recordDetails,
    documents: docsResult.documents,
    documentByVersionId,
    pages: docsResult.pages,
    regionsByDocument: docsResult.regionsByDocument,
    attributeValues,
    attributeValueById,
    reviewTasks,
    runs,
    evalRuns,
    canonicalIds: {
      record: "rec_canonical_abc123",
      wrongRowTaskId: findWrongRowTaskId(reviewTasks, attrsByRecord),
    },
  };
}

function stripInternalFields(av: WireAttrValue) {
  const { record_id: _r, attribute_code: _c, attribute_name: _n, risk_tier: _t, ...rest } = av;
  void _r;
  void _c;
  void _n;
  void _t;
  return rest;
}

const CLASS_CONFIDENCE_BY_STATUS: Partial<Record<RecordStatus, number>> = {
  class_unresolved: 0.41,
};

function buildRecordSummary(
  skeleton: RecordSkeleton,
  attrs: WireAttrValue[],
  rng: ReturnType<typeof createRng>,
  bindingsByRecord: Record<string, { documentVersionId: string }[]>,
) {
  const mandatory = attrs; // schemas here are ~all mandatory; see mocks/fixtures/taxonomy.ts
  const filled = mandatory.filter((a) => a.status !== "UNKNOWN").length;
  const accepted = mandatory.filter((a) => a.status === "ACCEPTED").length;
  const pendingReview = mandatory.filter(
    (a) => a.status === "NEEDS_REVIEW" || a.status === "NEEDS_APPROVAL",
  ).length;
  const unknown = mandatory.filter((a) => a.status === "UNKNOWN").length;
  const tier0Pending = mandatory.filter((a) => a.status === "NEEDS_APPROVAL").length;

  const cls: ClassRefWire | null =
    skeleton.classIndex === null
      ? null
      : {
          id: TAXONOMY[skeleton.classIndex].id,
          code: TAXONOMY[skeleton.classIndex].code,
          name: TAXONOMY[skeleton.classIndex].name,
          confidence: CLASS_CONFIDENCE_BY_STATUS[skeleton.targetStatus] ?? rng.range(0.9, 0.99, 2),
          provenance_kind: "DERIVED",
          signal: "rule+llm",
        };

  return {
    id: skeleton.id,
    mpn_raw: skeleton.mpnRaw,
    description_raw: skeleton.descriptionRaw,
    supplier_name: skeleton.supplierName,
    status: skeleton.targetStatus,
    class: cls,
    completeness: {
      mandatory_total: mandatory.length,
      filled,
      accepted,
      pending_review: pendingReview,
      unknown,
    },
    tier0_pending_count: tier0Pending,
    unknown_count: unknown,
    has_document: (bindingsByRecord[skeleton.id]?.length ?? 0) > 0,
    created_at: skeleton.createdAt,
  };
}

function findWrongRowTaskId(
  tasks: { id: string; attribute_value_id: string }[],
  attrsByRecord: Map<string, WireAttrValue[]>,
): string | null {
  const canonicalAttrs = attrsByRecord.get("rec_canonical_abc123") ?? [];
  const seatMaterial = canonicalAttrs.find((a) => a.attribute_code === "seat_material");
  if (!seatMaterial) return null;
  const task = tasks.find((t) => t.attribute_value_id === seatMaterial.id);
  return task?.id ?? null;
}

export type FixtureStore = ReturnType<typeof buildStore>;

let _store: FixtureStore | null = null;

/** Lazily built, then memoised for the life of the server process. */
export function getStore(): FixtureStore {
  if (!_store) _store = buildStore();
  return _store;
}
