/**
 * The fixture store — one deterministic, in-memory assembly of the whole canonical
 * dataset (docs/14-frontend-implementation-plan.md §4.2). Built once per server
 * process from a fixed seed; every mock route handler reads from this singleton.
 *
 * Order matters: taxonomy -> records -> documents (needs records) -> attribute values
 * (needs records + document bindings) -> review tasks (needs attribute values) ->
 * runs -> eval runs. Dashboard/queue aggregates are all *computed* from this data,
 * never hand-typed (risk F-3).
 *
 * **Live aggregates (F6).** Record-level `completeness` / `status` counts /
 * `tier0_pending_count` / `unknown_count` are *derived*, not stored: `records` is a
 * getter and `recordDetails` is a small class, both recomputing from the current
 * `attrsByRecordId` state on every access (`liveRecordSummary`). Before F6 these were
 * computed once in `buildStore()` and frozen into a plain array/Map — correct at
 * server-start, but a review decision (accept/reject/correct/approve) mutates the
 * underlying `WireAttrValue` objects in place (mocks/server/review-actions.ts) without
 * ever touching that frozen snapshot, so the catalog list, the record-detail header,
 * and every dashboard tile derived from `store.records` (mocks/fixtures/aggregates.ts)
 * kept reporting pre-decision numbers for the rest of the process's life. Only
 * `recordIdentities` (mpn/description/supplier/status/class/has_document/created_at —
 * fields review never touches, and the one review *does* touch via a documented
 * mutable exception, `class`) is still a plain built-once `Map`.
 */
import { createRng } from "./rng";
import { TAXONOMY } from "./taxonomy";
import { generateRecordSkeletons, type RecordSkeleton } from "./records";
import { generateDocuments, type RecordBinding } from "./documents";
import { generateAttributeValues } from "./attribute-values";
import { generateReviewTasks, type RecordIndexEntry } from "./review-tasks";
import { generateRuns } from "./runs";
import { generateEvalRuns } from "./eval-runs";
import type {
  AttributeValueStatus,
  EvidenceWire,
  ProvenanceKind,
  UnknownReason,
} from "@/lib/contracts/attribute-value";
import type { ClassRefWire, RecordStatus } from "@/lib/contracts/record";
import type { ReviewReasonCode } from "@/lib/contracts/review";

const SEED = 0x0f5f0e5c; // "F5F0E5C" — arbitrary, fixed. Never change without a reason.
const RECORD_COUNT = 240;

/** The full shape every object generated by mocks/fixtures/attribute-values.ts
 *  actually has — see the `[key: string]: unknown` extras noted there (record_id,
 *  attribute_code, attribute_name, risk_tier) plus the real wire fields. Kept explicit
 *  (not relying on an index signature) so downstream call sites get real structural
 *  checking instead of `unknown`. */
export interface WireAttrValue {
  id: string;
  record_id: string;
  attribute_code: string;
  attribute_name: string;
  risk_tier: 0 | 1 | 2 | 3;
  attribute: {
    code: string;
    name: string;
    datatype: string;
    risk_tier: 0 | 1 | 2 | 3;
    is_mandatory: boolean;
  };
  status: AttributeValueStatus;
  value_display: string | null;
  value_canonical: Record<string, unknown> | null;
  value_raw: string | null;
  unknown_reason: UnknownReason | null;
  provenance_kind: ProvenanceKind | null;
  confidence: number | null;
  evidence: EvidenceWire[];
  verification: {
    verdict: string;
    deterministic_check: string;
    rationale: string;
    verifier_model: string;
  } | null;
  created_at: string;
}

/** Matches mocks/fixtures/review-tasks.ts's `buildTask()` return shape. */
export interface WireReviewTask {
  id: string;
  record_id: string;
  record_mpn: string;
  record_description: string;
  attribute_value_id: string;
  attribute_code: string;
  attribute_name: string;
  risk_tier: 0 | 1 | 2 | 3;
  reason_code: ReviewReasonCode;
  state: "open" | "claimed" | "resolved" | "skipped";
  priority: number;
  assigned_to: string | null;
  proposed_value: WireAttrValue | null;
  rejection_reason: string | null;
  document_version_id: string | null;
  page: number | null;
  similar_task_count: number;
  opened_at: string;
  closed_at: string | null;
}

/** Matches mocks/fixtures/documents.ts's `buildDocumentWire()` return shape. */
export interface WireDocument {
  document_version_id: string;
  document_id: string;
  publisher: string;
  title: string;
  doc_type: string;
  page_count: number;
  parse_status: string;
  bound_record_count: number;
  first_seen_at: string;
  content_hash: string;
  source_url: string | null;
  fetched_at: string;
  effective_date: string | null;
  parse_quality: number | null;
  has_text_layer: boolean;
  used_ocr: boolean;
  pages: { n: number; width_px: number; height_px: number; dpi: number }[];
  regions_summary: { table_count: number; row_count: number };
}

/** The fields that never change once generated — identity, classification, binding
 *  existence. `class` is the one exception: `PATCH /records/{id}/class` mutates it in
 *  place (manual reclassification writes `HUMAN` provenance), so it lives here as a
 *  mutable object, not folded into a frozen summary. */
export interface RecordIdentity {
  id: string;
  mpn_raw: string;
  description_raw: string;
  supplier_name: string | null;
  status: RecordStatus;
  class: ClassRefWire | null;
  has_document: boolean;
  created_at: string;
  bindings: {
    document_version_id: string;
    region_id: string | null;
    confidence: number;
    signals: unknown;
  }[];
}

/** Completeness + the two counts derived from it, computed fresh from whatever is
 *  currently in `attrsByRecordId` — never cached (see `liveRecordSummary` below). */
function computeCompleteness(attrs: WireAttrValue[]) {
  // Schemas here are ~all mandatory (see mocks/fixtures/taxonomy.ts).
  const mandatory = attrs;
  const filled = mandatory.filter((a) => a.status !== "UNKNOWN").length;
  const accepted = mandatory.filter((a) => a.status === "ACCEPTED").length;
  const pendingReview = mandatory.filter(
    (a) => a.status === "NEEDS_REVIEW" || a.status === "NEEDS_APPROVAL",
  ).length;
  const unknown = mandatory.filter((a) => a.status === "UNKNOWN").length;
  const tier0Pending = mandatory.filter((a) => a.status === "NEEDS_APPROVAL").length;
  return {
    completeness: {
      mandatory_total: mandatory.length,
      filled,
      accepted,
      pending_review: pendingReview,
      unknown,
    },
    tier0_pending_count: tier0Pending,
    unknown_count: unknown,
  };
}

/** Merges a record's static identity with its *current* attribute state — this is the
 *  one function that produces a `RecordSummaryWire`, called fresh on every read so a
 *  review decision (accept/reject/correct/approve) is reflected the instant it happens,
 *  on the catalog list, the record header, and every dashboard aggregate derived from
 *  them (see the module doc comment: this fixes the F1/F5 stale-snapshot issue). */
function liveRecordSummary(identity: RecordIdentity, attrs: WireAttrValue[]) {
  return {
    id: identity.id,
    mpn_raw: identity.mpn_raw,
    description_raw: identity.description_raw,
    supplier_name: identity.supplier_name,
    status: identity.status,
    class: identity.class,
    has_document: identity.has_document,
    created_at: identity.created_at,
    ...computeCompleteness(attrs),
  };
}

/** A `Map`-shaped (`get`/`has`/`keys`) view over `recordIdentities` that composes a
 *  full `RecordDetail` (summary + bindings, still without `attributes`) fresh on every
 *  `.get()` — see `liveRecordSummary`. Kept as its own small class, rather than a plain
 *  `Map<string, RecordDetailWire>`, specifically so nothing can cache a detail object
 *  past the moment it was read. */
class LiveRecordDetails {
  constructor(
    private readonly identities: Map<string, RecordIdentity>,
    private readonly attrsByRecordId: Map<string, WireAttrValue[]>,
  ) {}

  get(id: string) {
    const identity = this.identities.get(id);
    if (!identity) return undefined;
    return {
      ...liveRecordSummary(identity, this.attrsByRecordId.get(id) ?? []),
      bindings: identity.bindings,
    };
  }

  has(id: string): boolean {
    return this.identities.has(id);
  }

  keys(): IterableIterator<string> {
    return this.identities.keys();
  }
}

function buildStore() {
  const rng = createRng(SEED);

  const skeletons = generateRecordSkeletons(rng, RECORD_COUNT);
  const docsResult = generateDocuments(rng, skeletons);
  const attributeValues = generateAttributeValues(
    rng,
    skeletons,
    docsResult.bindingsByRecord,
    docsResult.unparseableDocumentVersionId,
    docsResult.wrongRowEvidence,
  ) as WireAttrValue[];

  // `attrsByRecord` is the *current* one-per-attribute set that drives completeness,
  // RecordSummary counts, and GET /records/{id}'s `attributes` list — it must exclude
  // SUPERSEDED entries (injected by attribute-values.ts's `injectSupersessionChains`),
  // which exist only for individual lookup via `attributeValueById` below (the
  // `/attributes/{id}/explain` and `/attributes/{id}/history` routes), never as part of
  // a record's current attribute set.
  const attrsByRecord = new Map<string, WireAttrValue[]>();
  for (const av of attributeValues) {
    if (av.status === "SUPERSEDED") continue;
    const list = attrsByRecord.get(av.record_id) ?? [];
    list.push(av);
    attrsByRecord.set(av.record_id, list);
  }

  const skeletonById = new Map(skeletons.map((s) => [s.id, s]));

  const recordIdentities = new Map<string, RecordIdentity>(
    skeletons.map((skeleton) => [
      skeleton.id,
      buildRecordIdentity(skeleton, rng, docsResult.bindingsByRecord),
    ]),
  );

  const recordIndex = new Map<string, RecordIndexEntry>(
    skeletons.map((s) => [s.id, { id: s.id, mpnRaw: s.mpnRaw, descriptionRaw: s.descriptionRaw }]),
  );
  const bindingByRecord = new Map<string, { documentVersionId: string; page: number }>(
    Object.entries(docsResult.bindingsByRecord).map(([id, bindings]) => [
      id,
      { documentVersionId: bindings[0].documentVersionId, page: bindings[0].page },
    ]),
  );

  const reviewTasks = generateReviewTasks(
    rng,
    attributeValues,
    recordIndex,
    bindingByRecord,
  ) as WireReviewTask[];

  const runs = generateRuns();
  const evalRuns = generateEvalRuns();

  const attributeValueById = new Map(attributeValues.map((av) => [av.id, av]));
  const documentByVersionId = new Map(
    (docsResult.documents as WireDocument[]).map((d) => [d.document_version_id, d]),
  );

  return {
    taxonomy: TAXONOMY,
    skeletonById,
    /** Static identity per record (mutable only via `PATCH /records/{id}/class`).
     *  `records` and `recordDetails` below are both *computed from this on every
     *  access* — never read this directly for anything that should reconcile with the
     *  live mock state (risk F-3, and the F1/F5 stale-aggregate fix this module
     *  documents at the top). */
    recordIdentities,
    /** Every record's current summary, recomputed on each property access (a getter,
     *  not a stored array) — `GET /records`, `GET /catalog/pull`, and every dashboard
     *  aggregate in mocks/fixtures/aggregates.ts read this and so are live by
     *  construction, with no separate "refresh the snapshot" step to forget. */
    get records() {
      return [...recordIdentities.values()].map((identity) =>
        liveRecordSummary(identity, attrsByRecord.get(identity.id) ?? []),
      );
    },
    recordDetails: new LiveRecordDetails(recordIdentities, attrsByRecord),
    /** Live per-record attribute lists — the same `WireAttrValue` object references
     *  `attributeValueById` and review tasks' `proposed_value` hold, so a mutation via
     *  review-actions.ts is visible here immediately (see `recordDetails` above). */
    attrsByRecordId: attrsByRecord,
    documents: docsResult.documents,
    documentByVersionId,
    pages: docsResult.pages,
    regionsByDocument: docsResult.regionsByDocument,
    attributeValues,
    attributeValueById,
    reviewTasks,
    runs,
    evalRuns,
    canonicalIds: {
      record: "rec_canonical_abc123",
      wrongRowTaskId: findWrongRowTaskId(reviewTasks, attrsByRecord),
    },
  };
}

export function stripInternalFields(av: WireAttrValue) {
  const { record_id: _r, attribute_code: _c, attribute_name: _n, risk_tier: _t, ...rest } = av;
  void _r;
  void _c;
  void _n;
  void _t;
  return rest;
}

const CLASS_CONFIDENCE_BY_STATUS: Partial<Record<RecordStatus, number>> = {
  class_unresolved: 0.41,
};

/** Builds the static half of a record — everything review actions never mutate, plus
 *  `class` (a documented mutable exception: `PATCH /records/{id}/class`). Completeness
 *  and the counts derived from it are deliberately *not* computed here — see
 *  `liveRecordSummary`. */
function buildRecordIdentity(
  skeleton: RecordSkeleton,
  rng: ReturnType<typeof createRng>,
  bindingsByRecord: Record<string, RecordBinding[]>,
): RecordIdentity {
  const cls: ClassRefWire | null =
    skeleton.classIndex === null
      ? null
      : {
          id: TAXONOMY[skeleton.classIndex].id,
          code: TAXONOMY[skeleton.classIndex].code,
          name: TAXONOMY[skeleton.classIndex].name,
          confidence: CLASS_CONFIDENCE_BY_STATUS[skeleton.targetStatus] ?? rng.range(0.9, 0.99, 2),
          provenance_kind: "DERIVED",
          signal: "rule+llm",
        };

  const bindings = bindingsByRecord[skeleton.id] ?? [];

  return {
    id: skeleton.id,
    mpn_raw: skeleton.mpnRaw,
    description_raw: skeleton.descriptionRaw,
    supplier_name: skeleton.supplierName,
    status: skeleton.targetStatus,
    class: cls,
    has_document: bindings.length > 0,
    created_at: skeleton.createdAt,
    bindings: bindings.map((b) => ({
      document_version_id: b.documentVersionId,
      region_id: b.regionId,
      confidence: b.confidence,
      signals: b.signals,
    })),
  };
}

function findWrongRowTaskId(
  tasks: { id: string; attribute_value_id: string }[],
  attrsByRecord: Map<string, WireAttrValue[]>,
): string | null {
  const canonicalAttrs = attrsByRecord.get("rec_canonical_abc123") ?? [];
  const seatMaterial = canonicalAttrs.find((a) => a.attribute_code === "seat_material");
  if (!seatMaterial) return null;
  const task = tasks.find((t) => t.attribute_value_id === seatMaterial.id);
  return task?.id ?? null;
}

export type FixtureStore = ReturnType<typeof buildStore>;

let _store: FixtureStore | null = null;

/** Lazily built, then memoised for the life of the server process. */
export function getStore(): FixtureStore {
  if (!_store) _store = buildStore();
  return _store;
}
